package com.calculusmaster.pokecord.util.enums;

public enum StatisticType
{
    //Pokemon
    POKEMON_CAUGHT,
    POKEMON_RELEASED,
    POKEMON_EVOLVED,
    POKEMON_BRED,
    POKEMON_DYNAMAXED,
    POKEMON_PRESTIGED,
    EGGS_HATCHED,
    POKEMON_DEFEATED,
    POKEMON_FAINTED,

    //Moves
    MOVES_USED,
    ZMOVES_USED,
    MAX_MOVES_USED,
    MOVES_LEARNED,

    //Shop
    ITEMS_BOUGHT,
    TMS_BOUGHT,
    NATURES_BOUGHT,
    RARE_CANDIES_BOUGHT,
    MOVE_TUTORS_BOUGHT,

    //Market
    POKEMON_SOLD_MARKET,
    POKEMON_BOUGHT_MARKET,

    //Inventory
    CREDITS_SPENT,
    CREDITS_EARNED,
    ITEMS_ACQUIRED,
    TMS_ACQUIRED,

    //Duels
    PVP_DUELS_WON,
    PVP_DUELS_COMPLETED,
    WILD_DUELS_WON,
    WILD_DUELS_COMPLETED,
    TRAINER_DUELS_WON,
    TRAINER_DUELS_COMPLETED,
    ELITE_DUELS_WON,
    ELITE_DUELS_COMPLETED,
    RAIDS_WON,
    RAIDS_COMPLETED,
    RAID_POKEMON_CAUGHT,

    //Misc
    TRADES_COMPLETED,
    TASKS_COMPLETED,
    ;
}
