package com.calculusmaster.pokecord.util;

import java.util.*;

public class PokemonRarity
{
    public static final List<String> SPAWNS = new ArrayList<>();
    public static final Map<String, Rarity> POKEMON_RARITIES = new HashMap<>();

    public static final List<String> LEGENDARY = Arrays.asList("Articuno", "Galarian Articuno", "Moltres", "Galarian Moltres", "Zapdos", "Galarian Zapdos", "Mewtwo", "Mega Mewtwo X", "Mega Mewtwo Y", "Raikou", "Entei", "Suicune", "Lugia", "Ho Oh", "Regirock", "Regice", "Registeel", "Latias", "Mega Latias", "Latios", "Mega Latios", "Kyogre", "Primal Kyogre", "Groudon", "Primal Groudon", "Rayquaza", "Mega Rayquaza", "Deoxys", "Deoxys Attack", "Deoxys Defense", "Deoxys Speed", "Dialga", "Palkia", "Heatran", "Regigigas", "Giratina", "Origin Giratina", "Cresselia", "Darkrai", "Arceus", "Cobalion", "Terrakion", "Virizion", "Tornadus", "Thundurus", "Zekrom", "Reshiram", "Landorus", "Kyurem", "Black Kyurem", "White Kyurem", "Keldeo", "Xerneas", "Yveltal", "Zygarde", "Zygarde 10", "Zygarde Complete", "Volcanion", "Solgaleo", "Lunala", "Necrozma", "Dusk Mane Necrozma", "Dawn Wings Necrozma", "Ultra Necrozma", "Meltan", "Melmetal", "Zacian", "Zamazenta", "Eternatus", "Regieleki", "Regidrago", "Glastrier", "Spectrier", "Calyrex", "Ice Rider Calyrex", "Shadow Rider Calyrex");
    public static final List<String> MYTHICAL = Arrays.asList("Mew", "Celebi", "Jirachi", "Uxie", "Mesprit", "Azelf", "Phione", "Manaphy", "Shaymin", "Shaymin Sky", "Victini", "Meloetta Pirouette", "Genesect", "Diancie", "Mega Diancie", "Hoopa", "Hoopa Unbound", "Tapu Koko", "Tapu Lele", "Tapu Bulu", "Tapu Fini", "Magearna", "Marshadow", "Zeraora", "Zarude");
    public static final List<String> ULTRA_BEAST = Arrays.asList("Nihilego", "Buzzwole", "Pheromosa", "Xurkitree", "Celesteela", "Kartana", "Guzzlord", "Poipole", "Naganadel", "Stakataka", "Blacephalon");
    public static final List<String> MEGA = Arrays.asList("Mega Venusaur", "Mega Charizard X", "Mega Charizard Y", "Mega Blastoise", "Mega Alakazam", "Mega Gengar", "Mega Kangaskhan", "Mega Pinsir", "Mega Gyarados", "Mega Aerodactyl", "Mega Ampharos", "Mega Scizor", "Mega Heracross", "Mega Houndoom", "Mega Tyranitar", "Mega Blaziken", "Mega Gardevoir", "Mega Mawile", "Mega Aggron", "Mega Medicham", "Mega Manectric", "Mega Banette", "Mega Absol", "Mega Garchomp", "Mega Lucario", "Mega Abomasnow", "Mega Beedrill", "Mega Pidgeot", "Mega Slowbro", "Mega Steelix", "Mega Sceptile", "Mega Swampert", "Mega Sableye", "Mega Sharpedo", "Mega Camerupt", "Mega Altaria", "Mega Glalie", "Mega Salamence", "Mega Lopunny", "Mega Gallade", "Mega Audino", "Mega Metagross");

    public static void init()
    {

        //Gen 1

        PokemonRarity.add("Bulbasaur", Rarity.SILVER);
        PokemonRarity.add("Ivysaur", Rarity.GOLD);
        PokemonRarity.add("Venusaur", Rarity.DIAMOND);
        PokemonRarity.add("Charmander", Rarity.SILVER);
        PokemonRarity.add("Charmeleon", Rarity.GOLD);
        PokemonRarity.add("Charizard", Rarity.DIAMOND);
        PokemonRarity.add("Squirtle", Rarity.SILVER);
        PokemonRarity.add("Wartortle", Rarity.GOLD);
        PokemonRarity.add("Blastoise", Rarity.DIAMOND);
        PokemonRarity.add("Caterpie", Rarity.COPPER);
        PokemonRarity.add("Metapod", Rarity.COPPER);
        PokemonRarity.add("Butterfree", Rarity.SILVER);
        PokemonRarity.add("Weedle", Rarity.COPPER);
        PokemonRarity.add("Kakuna", Rarity.COPPER);
        PokemonRarity.add("Beedrill", Rarity.GOLD);
        PokemonRarity.add("Pidgey", Rarity.COPPER);
        PokemonRarity.add("Pidgeotto", Rarity.SILVER);
        PokemonRarity.add("Pidgeot", Rarity.SILVER);
        PokemonRarity.add("Rattata", Rarity.COPPER);
        PokemonRarity.add("Alolan Rattata", Rarity.SILVER);
        PokemonRarity.add("Raticate", Rarity.SILVER);
        PokemonRarity.add("Alolan Raticate", Rarity.GOLD);
        PokemonRarity.add("Spearow", Rarity.COPPER);
        PokemonRarity.add("Fearow", Rarity.SILVER);
        PokemonRarity.add("Ekans", Rarity.COPPER);
        PokemonRarity.add("Arbok", Rarity.SILVER);
        PokemonRarity.add("Pikachu", Rarity.SILVER);
        PokemonRarity.add("Raichu", Rarity.GOLD);
        PokemonRarity.add("Alolan Raichu", Rarity.DIAMOND);
        PokemonRarity.add("Sandshrew", Rarity.COPPER);
        PokemonRarity.add("Alolan Sandshrew", Rarity.SILVER);
        PokemonRarity.add("Sandslash", Rarity.SILVER);
        PokemonRarity.add("Alolan Sandslash", Rarity.GOLD);
        PokemonRarity.add("NidoranF", Rarity.COPPER);
        PokemonRarity.add("Nidorina", Rarity.SILVER);
        PokemonRarity.add("Nidoqueen", Rarity.DIAMOND);
        PokemonRarity.add("NidoranM", Rarity.COPPER);
        PokemonRarity.add("Nidorino", Rarity.SILVER);
        PokemonRarity.add("Nidoking", Rarity.DIAMOND);
        PokemonRarity.add("Clefairy", Rarity.SILVER);
        PokemonRarity.add("Clefable", Rarity.GOLD);
        PokemonRarity.add("Vulpix", Rarity.COPPER);
        PokemonRarity.add("Alolan Vulpix", Rarity.SILVER);
        PokemonRarity.add("Ninetales", Rarity.SILVER);
        PokemonRarity.add("Alolan Ninetales", Rarity.GOLD);
        PokemonRarity.add("Jigglypuff", Rarity.COPPER);
        PokemonRarity.add("Wigglytuff", Rarity.SILVER);
        PokemonRarity.add("Zubat", Rarity.COPPER);
        PokemonRarity.add("Golbat", Rarity.SILVER);
        PokemonRarity.add("Oddish", Rarity.COPPER);
        PokemonRarity.add("Gloom", Rarity.SILVER);
        PokemonRarity.add("Vileplume", Rarity.GOLD);
        PokemonRarity.add("Paras", Rarity.COPPER);
        PokemonRarity.add("Parasect", Rarity.SILVER);
        PokemonRarity.add("Venonat", Rarity.COPPER);
        PokemonRarity.add("Venomoth", Rarity.SILVER);
        PokemonRarity.add("Diglett", Rarity.COPPER);
        PokemonRarity.add("Alolan Diglett", Rarity.SILVER);
        PokemonRarity.add("Dugtrio", Rarity.SILVER);
        PokemonRarity.add("Alolan Dugtrio", Rarity.SILVER);
        PokemonRarity.add("Meowth", Rarity.COPPER);
        PokemonRarity.add("Alolan Meowth", Rarity.SILVER);
        PokemonRarity.add("Galarian Meowth", Rarity.SILVER);
        PokemonRarity.add("Persian", Rarity.SILVER);
        PokemonRarity.add("Alolan Persian", Rarity.SILVER);
        PokemonRarity.add("Psyduck", Rarity.COPPER);
        PokemonRarity.add("Golduck", Rarity.SILVER);
        PokemonRarity.add("Mankey", Rarity.COPPER);
        PokemonRarity.add("Primeape", Rarity.SILVER);
        PokemonRarity.add("Growlithe", Rarity.SILVER);
        PokemonRarity.add("Arcanine", Rarity.GOLD);
        PokemonRarity.add("Poliwag", Rarity.COPPER);
        PokemonRarity.add("Poliwhirl", Rarity.SILVER);
        PokemonRarity.add("Poliwrath", Rarity.GOLD);
        PokemonRarity.add("Abra", Rarity.COPPER);
        PokemonRarity.add("Kadabra", Rarity.SILVER);
        PokemonRarity.add("Alakazam", Rarity.GOLD);
        PokemonRarity.add("Machop", Rarity.COPPER);
        PokemonRarity.add("Machoke", Rarity.SILVER);
        PokemonRarity.add("Machamp", Rarity.GOLD);
        PokemonRarity.add("Bellsprout", Rarity.COPPER);
        PokemonRarity.add("Weepinbell", Rarity.SILVER);
        PokemonRarity.add("Victreebel", Rarity.GOLD);
        PokemonRarity.add("Tentacool", Rarity.COPPER);
        PokemonRarity.add("Tentacruel", Rarity.SILVER);
        PokemonRarity.add("Geodude", Rarity.COPPER);
        PokemonRarity.add("Alolan Geodude", Rarity.SILVER);
        PokemonRarity.add("Graveler", Rarity.SILVER);
        PokemonRarity.add("Alolan Graveler", Rarity.GOLD);
        PokemonRarity.add("Golem", Rarity.GOLD);
        PokemonRarity.add("Alolan Golem", Rarity.DIAMOND);
        PokemonRarity.add("Ponyta", Rarity.COPPER);
        PokemonRarity.add("Galarian Ponyta", Rarity.SILVER);
        PokemonRarity.add("Rapidash", Rarity.SILVER);
        PokemonRarity.add("Galarian Rapidash", Rarity.SILVER);
        PokemonRarity.add("Slowpoke", Rarity.COPPER);
        PokemonRarity.add("Galarian Slowpoke", Rarity.SILVER);
        PokemonRarity.add("Slowbro", Rarity.SILVER);
        PokemonRarity.add("Galarian Slowbro", Rarity.SILVER);
        PokemonRarity.add("Magnemite", Rarity.COPPER);
        PokemonRarity.add("Magneton", Rarity.SILVER);
        PokemonRarity.add("Farfetchd", Rarity.SILVER);
        PokemonRarity.add("Galarian Farfetchd", Rarity.GOLD);
        PokemonRarity.add("Doduo", Rarity.COPPER);
        PokemonRarity.add("Dodrio", Rarity.SILVER);
        PokemonRarity.add("Seel", Rarity.COPPER);
        PokemonRarity.add("Dewgong", Rarity.SILVER);
        PokemonRarity.add("Grimer", Rarity.COPPER);
        PokemonRarity.add("Alolan Grimer", Rarity.SILVER);
        PokemonRarity.add("Muk", Rarity.SILVER);
        PokemonRarity.add("Alolan Muk", Rarity.SILVER);
        PokemonRarity.add("Shellder", Rarity.COPPER);
        PokemonRarity.add("Cloyster", Rarity.SILVER);
        PokemonRarity.add("Gastly", Rarity.COPPER);
        PokemonRarity.add("Haunter", Rarity.SILVER);
        PokemonRarity.add("Gengar", Rarity.GOLD);
        PokemonRarity.add("Onix", Rarity.COPPER);
        PokemonRarity.add("Drowzee", Rarity.COPPER);
        PokemonRarity.add("Hypno", Rarity.SILVER);
        PokemonRarity.add("Krabby", Rarity.COPPER);
        PokemonRarity.add("Kingler", Rarity.SILVER);
        PokemonRarity.add("Voltorb", Rarity.COPPER);
        PokemonRarity.add("Electrode", Rarity.SILVER);
        PokemonRarity.add("Exeggcute", Rarity.COPPER);
        PokemonRarity.add("Exeggutor", Rarity.SILVER);
        PokemonRarity.add("Alolan Exeggutor", Rarity.SILVER);
        PokemonRarity.add("Cubone", Rarity.COPPER);
        PokemonRarity.add("Marowak", Rarity.SILVER);
        PokemonRarity.add("Alolan Marowak", Rarity.SILVER);
        PokemonRarity.add("Hitmonlee", Rarity.SILVER);
        PokemonRarity.add("Hitmonchan", Rarity.SILVER);
        PokemonRarity.add("Lickitung", Rarity.SILVER);
        PokemonRarity.add("Koffing", Rarity.COPPER);
        PokemonRarity.add("Weezing", Rarity.SILVER);
        PokemonRarity.add("Galarian Weezing", Rarity.SILVER);
        PokemonRarity.add("Rhyhorn", Rarity.COPPER);
        PokemonRarity.add("Rhydon", Rarity.SILVER);
        PokemonRarity.add("Chansey", Rarity.SILVER);
        PokemonRarity.add("Tangela", Rarity.SILVER);
        PokemonRarity.add("Kangaskhan", Rarity.GOLD);
        PokemonRarity.add("Horsea", Rarity.COPPER);
        PokemonRarity.add("Seadra", Rarity.SILVER);
        PokemonRarity.add("Goldeen", Rarity.COPPER);
        PokemonRarity.add("Seaking", Rarity.SILVER);
        PokemonRarity.add("Staryu", Rarity.COPPER);
        PokemonRarity.add("Starmie", Rarity.SILVER);
        PokemonRarity.add("Mr Mime", Rarity.COPPER);
        PokemonRarity.add("Galarian Mr Mime", Rarity.SILVER);
        PokemonRarity.add("Scyther", Rarity.COPPER);
        PokemonRarity.add("Jynx", Rarity.SILVER);
        PokemonRarity.add("Electabuzz", Rarity.SILVER);
        PokemonRarity.add("Magmar", Rarity.SILVER);
        PokemonRarity.add("Pinsir", Rarity.SILVER);
        PokemonRarity.add("Tauros", Rarity.SILVER);
        PokemonRarity.add("Magikarp", Rarity.COPPER);
        PokemonRarity.add("Gyarados", Rarity.SILVER);
        PokemonRarity.add("Lapras", Rarity.SILVER);
        PokemonRarity.add("Ditto", Rarity.SILVER);
        PokemonRarity.add("Eevee", Rarity.COPPER);
        PokemonRarity.add("Vaporeon", Rarity.SILVER);
        PokemonRarity.add("Jolteon", Rarity.SILVER);
        PokemonRarity.add("Flareon", Rarity.SILVER);
        PokemonRarity.add("Porygon", Rarity.COPPER);
        PokemonRarity.add("Omanyte", Rarity.SILVER);
        PokemonRarity.add("Omastar", Rarity.GOLD);
        PokemonRarity.add("Kabuto", Rarity.SILVER);
        PokemonRarity.add("Kabutops", Rarity.GOLD);
        PokemonRarity.add("Aerodactyl", Rarity.SILVER);
        PokemonRarity.add("Snorlax", Rarity.SILVER);
        PokemonRarity.add("Articuno", Rarity.LEGENDARY);
        PokemonRarity.add("Galarian Articuno", Rarity.LEGENDARY);
        PokemonRarity.add("Zapdos", Rarity.LEGENDARY);
        PokemonRarity.add("Galarian Zapdos", Rarity.LEGENDARY);
        PokemonRarity.add("Moltres", Rarity.LEGENDARY);
        PokemonRarity.add("Galarian Moltres", Rarity.LEGENDARY);
        PokemonRarity.add("Dratini", Rarity.COPPER);
        PokemonRarity.add("Dragonair", Rarity.SILVER);
        PokemonRarity.add("Dragonite", Rarity.GOLD);
        PokemonRarity.add("Mewtwo", Rarity.LEGENDARY);
        PokemonRarity.add("Mew", Rarity.MYTHICAL);

        //Gen 2

        PokemonRarity.add("Chikorita", Rarity.SILVER);
        PokemonRarity.add("Bayleef", Rarity.GOLD);
        PokemonRarity.add("Meganium", Rarity.DIAMOND);
        PokemonRarity.add("Cyndaquil", Rarity.SILVER);
        PokemonRarity.add("Quilava", Rarity.GOLD);
        PokemonRarity.add("Typhlosion", Rarity.DIAMOND);
        PokemonRarity.add("Totodile", Rarity.SILVER);
        PokemonRarity.add("Croconaw", Rarity.GOLD);
        PokemonRarity.add("Feraligatr", Rarity.DIAMOND);
        PokemonRarity.add("Sentret", Rarity.COPPER);
        PokemonRarity.add("Furret", Rarity.SILVER);
        PokemonRarity.add("Hoothoot", Rarity.COPPER);
        PokemonRarity.add("Noctowl", Rarity.SILVER);
        PokemonRarity.add("Ledyba", Rarity.COPPER);
        PokemonRarity.add("Ledian", Rarity.SILVER);
        PokemonRarity.add("Spinarak", Rarity.COPPER);
        PokemonRarity.add("Ariados", Rarity.SILVER);
        PokemonRarity.add("Crobat", Rarity.GOLD);
        PokemonRarity.add("Chinchou", Rarity.COPPER);
        PokemonRarity.add("Lanturn", Rarity.SILVER);
        PokemonRarity.add("Pichu", Rarity.SILVER);
        PokemonRarity.add("Cleffa", Rarity.SILVER);
        PokemonRarity.add("Igglybuff", Rarity.SILVER);
        PokemonRarity.add("Togepi", Rarity.SILVER);
        PokemonRarity.add("Togetic", Rarity.GOLD);
        PokemonRarity.add("Natu", Rarity.SILVER);
        PokemonRarity.add("Xatu", Rarity.SILVER);
        PokemonRarity.add("Mareep", Rarity.COPPER);
        PokemonRarity.add("Flaaffy", Rarity.SILVER);
        PokemonRarity.add("Ampharos", Rarity.GOLD);
        PokemonRarity.add("Bellossom", Rarity.SILVER);
        PokemonRarity.add("Marill", Rarity.COPPER);
        PokemonRarity.add("Azumarill", Rarity.SILVER);
        PokemonRarity.add("Sudowoodo", Rarity.SILVER);
        PokemonRarity.add("Politoed", Rarity.SILVER);
        PokemonRarity.add("Hoppip", Rarity.COPPER);
        PokemonRarity.add("Skiploom", Rarity.SILVER);
        PokemonRarity.add("Jumpluff", Rarity.GOLD);
        PokemonRarity.add("Aipom", Rarity.COPPER);
        PokemonRarity.add("Sunkern", Rarity.COPPER);
        PokemonRarity.add("Sunflora", Rarity.COPPER);
        PokemonRarity.add("Yanma", Rarity.COPPER);
        PokemonRarity.add("Wooper", Rarity.COPPER);
        PokemonRarity.add("Quagsire", Rarity.SILVER);
        PokemonRarity.add("Espeon", Rarity.GOLD);
        PokemonRarity.add("Umbreon", Rarity.GOLD);
        PokemonRarity.add("Murkrow", Rarity.COPPER);
        PokemonRarity.add("Slowking", Rarity.GOLD);
        PokemonRarity.add("Galarian Slowking", Rarity.GOLD);
        PokemonRarity.add("Misdreavus", Rarity.COPPER);
        PokemonRarity.add("Unown", Rarity.SILVER);
        PokemonRarity.add("Wobbuffet", Rarity.SILVER);
        PokemonRarity.add("Girafarig", Rarity.COPPER);
        PokemonRarity.add("Pineco", Rarity.COPPER);
        PokemonRarity.add("Forretress", Rarity.SILVER);
        PokemonRarity.add("Dunsparce", Rarity.SILVER);
        PokemonRarity.add("Gligar", Rarity.COPPER);
        PokemonRarity.add("Steelix", Rarity.GOLD);
        PokemonRarity.add("Snubbull", Rarity.COPPER);
        PokemonRarity.add("Granbull", Rarity.SILVER);
        PokemonRarity.add("Qwilfish", Rarity.COPPER);
        PokemonRarity.add("Scizor", Rarity.SILVER);
        PokemonRarity.add("Shuckle", Rarity.COPPER);
        PokemonRarity.add("Heracross", Rarity.SILVER);
        PokemonRarity.add("Sneasel", Rarity.COPPER);
        PokemonRarity.add("Teddiursa", Rarity.COPPER);
        PokemonRarity.add("Ursaring", Rarity.SILVER);
        PokemonRarity.add("Slugma", Rarity.COPPER);
        PokemonRarity.add("Magcargo", Rarity.SILVER);
        PokemonRarity.add("Swinub", Rarity.COPPER);
        PokemonRarity.add("Piloswine", Rarity.SILVER);
        PokemonRarity.add("Corsola", Rarity.COPPER);
        PokemonRarity.add("Galarian Corsola", Rarity.COPPER);
        PokemonRarity.add("Remoraid", Rarity.COPPER);
        PokemonRarity.add("Octillery", Rarity.SILVER);
        PokemonRarity.add("Delibird", Rarity.SILVER);
        PokemonRarity.add("Mantine", Rarity.COPPER);
        PokemonRarity.add("Skarmory", Rarity.SILVER);
        PokemonRarity.add("Houndour", Rarity.COPPER);
        PokemonRarity.add("Houndoom", Rarity.SILVER);
        PokemonRarity.add("Kingdra", Rarity.GOLD);
        PokemonRarity.add("Phanpy", Rarity.COPPER);
        PokemonRarity.add("Donphan", Rarity.SILVER);
        PokemonRarity.add("Porygon2", Rarity.SILVER);
        PokemonRarity.add("Stantler", Rarity.COPPER);
        PokemonRarity.add("Smeargle", Rarity.SILVER);
        PokemonRarity.add("Tyrogue", Rarity.COPPER);
        PokemonRarity.add("Hitmontop", Rarity.SILVER);
        PokemonRarity.add("Smoochum", Rarity.COPPER);
        PokemonRarity.add("Elekid", Rarity.COPPER);
        PokemonRarity.add("Magby", Rarity.COPPER);
        PokemonRarity.add("Miltank", Rarity.COPPER);
        PokemonRarity.add("Blissey", Rarity.GOLD);
        PokemonRarity.add("Raikou", Rarity.LEGENDARY);
        PokemonRarity.add("Entei", Rarity.LEGENDARY);
        PokemonRarity.add("Suicune", Rarity.LEGENDARY);
        PokemonRarity.add("Larvitar", Rarity.COPPER);
        PokemonRarity.add("Pupitar", Rarity.SILVER);
        PokemonRarity.add("Tyranitar", Rarity.GOLD);
        PokemonRarity.add("Lugia", Rarity.LEGENDARY);
        PokemonRarity.add("Ho Oh", Rarity.LEGENDARY);
        PokemonRarity.add("Celebi", Rarity.MYTHICAL);

        //Gen 3

        PokemonRarity.add("Treecko", Rarity.SILVER);
        PokemonRarity.add("Grovyle", Rarity.GOLD);
        PokemonRarity.add("Sceptile", Rarity.DIAMOND);
        PokemonRarity.add("Torchic", Rarity.SILVER);
        PokemonRarity.add("Combusken", Rarity.GOLD);
        PokemonRarity.add("Blaziken", Rarity.DIAMOND);
        PokemonRarity.add("Mudkip", Rarity.SILVER);
        PokemonRarity.add("Marshtomp", Rarity.GOLD);
        PokemonRarity.add("Swampert", Rarity.DIAMOND);
        PokemonRarity.add("Poochyena", Rarity.COPPER);
        PokemonRarity.add("Mightyena", Rarity.SILVER);
        PokemonRarity.add("Zigzagoon", Rarity.COPPER);
        PokemonRarity.add("Galarian Zigzagoon", Rarity.SILVER);
        PokemonRarity.add("Linoone", Rarity.SILVER);
        PokemonRarity.add("Galarian Linoone", Rarity.GOLD);
        PokemonRarity.add("Wurmple", Rarity.COPPER);
        PokemonRarity.add("Silcoon", Rarity.COPPER);
        PokemonRarity.add("Beautifly", Rarity.SILVER);
        PokemonRarity.add("Cascoon", Rarity.COPPER);
        PokemonRarity.add("Dustox", Rarity.SILVER);
        PokemonRarity.add("Lotad", Rarity.COPPER);
        PokemonRarity.add("Lombre", Rarity.SILVER);
        PokemonRarity.add("Ludicolo", Rarity.GOLD);
        PokemonRarity.add("Seedot", Rarity.COPPER);
        PokemonRarity.add("Nuzleaf", Rarity.SILVER);
        PokemonRarity.add("Shiftry", Rarity.GOLD);
        PokemonRarity.add("Taillow", Rarity.COPPER);
        PokemonRarity.add("Swellow", Rarity.SILVER);
        PokemonRarity.add("Wingull", Rarity.COPPER);
        PokemonRarity.add("Pelipper", Rarity.SILVER);
        PokemonRarity.add("Ralts", Rarity.COPPER);
        PokemonRarity.add("Kirlia", Rarity.SILVER);
        PokemonRarity.add("Gardevoir", Rarity.GOLD);
        PokemonRarity.add("Surskit", Rarity.COPPER);
        PokemonRarity.add("Masquerain", Rarity.SILVER);
        PokemonRarity.add("Shroomish", Rarity.COPPER);
        PokemonRarity.add("Breloom", Rarity.SILVER);
        PokemonRarity.add("Slakoth", Rarity.COPPER);
        PokemonRarity.add("Vigoroth", Rarity.SILVER);
        PokemonRarity.add("Slaking", Rarity.GOLD);
        PokemonRarity.add("Nincada", Rarity.COPPER);
        PokemonRarity.add("Ninjask", Rarity.SILVER);
        PokemonRarity.add("Shedinja", Rarity.SILVER);
        PokemonRarity.add("Whismur", Rarity.COPPER);
        PokemonRarity.add("Loudred", Rarity.SILVER);
        PokemonRarity.add("Exploud", Rarity.GOLD);
        PokemonRarity.add("Makuhita", Rarity.COPPER);
        PokemonRarity.add("Hariyama", Rarity.SILVER);
        PokemonRarity.add("Azurill", Rarity.COPPER);
        PokemonRarity.add("Nosepass", Rarity.COPPER);
        PokemonRarity.add("Skitty", Rarity.COPPER);
        PokemonRarity.add("Delcatty", Rarity.SILVER);
        PokemonRarity.add("Sableye", Rarity.SILVER);
        PokemonRarity.add("Mawile", Rarity.SILVER);
        PokemonRarity.add("Aron", Rarity.COPPER);
        PokemonRarity.add("Lairon", Rarity.SILVER);
        PokemonRarity.add("Aggron", Rarity.GOLD);
        PokemonRarity.add("Meditite", Rarity.SILVER);
        PokemonRarity.add("Medicham", Rarity.GOLD);
        PokemonRarity.add("Electrike", Rarity.SILVER);
        PokemonRarity.add("Manectric", Rarity.GOLD);
        PokemonRarity.add("Plusle", Rarity.COPPER);
        PokemonRarity.add("Minun", Rarity.COPPER);
        PokemonRarity.add("Volbeat", Rarity.COPPER);
        PokemonRarity.add("Illumise", Rarity.COPPER);
        PokemonRarity.add("Roselia", Rarity.SILVER);
        PokemonRarity.add("Gulpin", Rarity.COPPER);
        PokemonRarity.add("Swalot", Rarity.SILVER);
        PokemonRarity.add("Carvanha", Rarity.COPPER);
        PokemonRarity.add("Sharpedo", Rarity.SILVER);
        PokemonRarity.add("Wailmer", Rarity.COPPER);
        PokemonRarity.add("Wailord", Rarity.SILVER);
        PokemonRarity.add("Numel", Rarity.COPPER);
        PokemonRarity.add("Camerupt", Rarity.SILVER);
        PokemonRarity.add("Torkoal", Rarity.COPPER);
        PokemonRarity.add("Spoink", Rarity.COPPER);
        PokemonRarity.add("Grumpig", Rarity.SILVER);
        PokemonRarity.add("Spinda", Rarity.COPPER);
        PokemonRarity.add("Trapinch", Rarity.COPPER);
        PokemonRarity.add("Vibrava", Rarity.SILVER);
        PokemonRarity.add("Flygon", Rarity.GOLD);
        PokemonRarity.add("Cacnea", Rarity.COPPER);
        PokemonRarity.add("Cacturne", Rarity.SILVER);
        PokemonRarity.add("Swablu", Rarity.COPPER);
        PokemonRarity.add("Altaria", Rarity.SILVER);
        PokemonRarity.add("Zangoose", Rarity.COPPER);
        PokemonRarity.add("Seviper", Rarity.COPPER);
        PokemonRarity.add("Lunatone", Rarity.COPPER);
        PokemonRarity.add("Solrock", Rarity.COPPER);
        PokemonRarity.add("Barboach", Rarity.COPPER);
        PokemonRarity.add("Whiscash", Rarity.SILVER);
        PokemonRarity.add("Corphish", Rarity.COPPER);
        PokemonRarity.add("Crawdaunt", Rarity.SILVER);
        PokemonRarity.add("Baltoy", Rarity.COPPER);
        PokemonRarity.add("Claydol", Rarity.SILVER);
        PokemonRarity.add("Lileep", Rarity.COPPER);
        PokemonRarity.add("Cradily", Rarity.SILVER);
        PokemonRarity.add("Anorith", Rarity.COPPER);
        PokemonRarity.add("Armaldo", Rarity.SILVER);
        PokemonRarity.add("Feebas", Rarity.COPPER);
        PokemonRarity.add("Milotic", Rarity.SILVER);
        PokemonRarity.add("Castform", Rarity.COPPER);
        PokemonRarity.add("Kecleon", Rarity.COPPER);
        PokemonRarity.add("Shuppet", Rarity.COPPER);
        PokemonRarity.add("Banette", Rarity.SILVER);
        PokemonRarity.add("Duskull", Rarity.COPPER);
        PokemonRarity.add("Dusclops", Rarity.SILVER);
        PokemonRarity.add("Tropius", Rarity.COPPER);
        PokemonRarity.add("Chimecho", Rarity.COPPER);
        PokemonRarity.add("Absol", Rarity.SILVER);
        PokemonRarity.add("Wynaut", Rarity.COPPER);
        PokemonRarity.add("Snorunt", Rarity.COPPER);
        PokemonRarity.add("Glalie", Rarity.SILVER);
        PokemonRarity.add("Spheal", Rarity.COPPER);
        PokemonRarity.add("Sealeo", Rarity.SILVER);
        PokemonRarity.add("Walrein", Rarity.GOLD);
        PokemonRarity.add("Clamperl", Rarity.COPPER);
        PokemonRarity.add("Huntail", Rarity.SILVER);
        PokemonRarity.add("Gorebyss", Rarity.SILVER);
        PokemonRarity.add("Relicanth", Rarity.COPPER);
        PokemonRarity.add("Luvdisc", Rarity.COPPER);
        PokemonRarity.add("Bagon", Rarity.COPPER);
        PokemonRarity.add("Shelgon", Rarity.SILVER);
        PokemonRarity.add("Salamence", Rarity.GOLD);
        PokemonRarity.add("Beldum", Rarity.SILVER);
        PokemonRarity.add("Metang", Rarity.GOLD);
        PokemonRarity.add("Metagross", Rarity.DIAMOND);
        PokemonRarity.add("Regirock", Rarity.LEGENDARY);
        PokemonRarity.add("Regice", Rarity.LEGENDARY);
        PokemonRarity.add("Registeel", Rarity.LEGENDARY);
        PokemonRarity.add("Latias", Rarity.LEGENDARY);
        PokemonRarity.add("Latios", Rarity.LEGENDARY);
        PokemonRarity.add("Kyogre", Rarity.LEGENDARY);
        PokemonRarity.add("Groudon", Rarity.LEGENDARY);
        PokemonRarity.add("Rayquaza", Rarity.LEGENDARY);
        PokemonRarity.add("Jirachi", Rarity.MYTHICAL);
        PokemonRarity.add("Deoxys", Rarity.LEGENDARY);
        PokemonRarity.add("Deoxys Attack", Rarity.EXTREME);
        PokemonRarity.add("Deoxys Defense", Rarity.EXTREME);
        PokemonRarity.add("Deoxys Speed", Rarity.EXTREME);

        //Gen 4

        PokemonRarity.add("Turtwig", Rarity.SILVER);
        PokemonRarity.add("Grotle", Rarity.GOLD);
        PokemonRarity.add("Torterra", Rarity.DIAMOND);
        PokemonRarity.add("Chimchar", Rarity.SILVER);
        PokemonRarity.add("Monferno", Rarity.GOLD);
        PokemonRarity.add("Infernape", Rarity.DIAMOND);
        PokemonRarity.add("Piplup", Rarity.SILVER);
        PokemonRarity.add("Prinplup", Rarity.GOLD);
        PokemonRarity.add("Empoleon", Rarity.DIAMOND);
        PokemonRarity.add("Starly", Rarity.COPPER);
        PokemonRarity.add("Staravia", Rarity.SILVER);
        PokemonRarity.add("Staraptor", Rarity.GOLD);
        PokemonRarity.add("Bidoof", Rarity.COPPER);
        PokemonRarity.add("Bibarel", Rarity.SILVER);
        PokemonRarity.add("Kricketot", Rarity.COPPER);
        PokemonRarity.add("Kricketune", Rarity.SILVER);
        PokemonRarity.add("Shinx", Rarity.COPPER);
        PokemonRarity.add("Luxio", Rarity.SILVER);
        PokemonRarity.add("Luxray", Rarity.GOLD);
        PokemonRarity.add("Budew", Rarity.COPPER);
        PokemonRarity.add("Roserade", Rarity.GOLD);
        PokemonRarity.add("Cranidos", Rarity.COPPER);
        PokemonRarity.add("Rampardos", Rarity.SILVER);
        PokemonRarity.add("Shieldon", Rarity.COPPER);
        PokemonRarity.add("Bastiodon", Rarity.SILVER);
        PokemonRarity.add("Burmy", Rarity.COPPER);
        PokemonRarity.add("Wormadam", Rarity.SILVER);
        PokemonRarity.add("Mothim", Rarity.SILVER);
        PokemonRarity.add("Combee", Rarity.COPPER);
        PokemonRarity.add("Vespiquen", Rarity.SILVER);
        PokemonRarity.add("Pachirisu", Rarity.COPPER);
        PokemonRarity.add("Buizel", Rarity.COPPER);
        PokemonRarity.add("Floatzel", Rarity.SILVER);
        PokemonRarity.add("Cherubi", Rarity.COPPER);
        PokemonRarity.add("Cherrim", Rarity.SILVER);
        PokemonRarity.add("Shellos", Rarity.COPPER);
        PokemonRarity.add("Gastrodon", Rarity.SILVER);
        PokemonRarity.add("Ambipom", Rarity.SILVER);
        PokemonRarity.add("Drifloon", Rarity.COPPER);
        PokemonRarity.add("Drifblim", Rarity.SILVER);
        PokemonRarity.add("Buneary", Rarity.COPPER);
        PokemonRarity.add("Lopunny", Rarity.SILVER);
        PokemonRarity.add("Mismagius", Rarity.SILVER);
        PokemonRarity.add("Honchkrow", Rarity.SILVER);
        PokemonRarity.add("Glameow", Rarity.COPPER);
        PokemonRarity.add("Purugly", Rarity.SILVER);
        PokemonRarity.add("Chingling", Rarity.COPPER);
        PokemonRarity.add("Stunky", Rarity.COPPER);
        PokemonRarity.add("Skuntank", Rarity.SILVER);
        PokemonRarity.add("Bronzor", Rarity.COPPER);
        PokemonRarity.add("Bronzong", Rarity.SILVER);
        PokemonRarity.add("Bonsly", Rarity.COPPER);
        PokemonRarity.add("Mime Jr", Rarity.COPPER);
        PokemonRarity.add("Happiny", Rarity.COPPER);
        PokemonRarity.add("Chatot", Rarity.COPPER);
        PokemonRarity.add("Spiritomb", Rarity.COPPER);
        PokemonRarity.add("Gible", Rarity.COPPER);
        PokemonRarity.add("Gabite", Rarity.SILVER);
        PokemonRarity.add("Garchomp", Rarity.GOLD);
        PokemonRarity.add("Munchlax", Rarity.COPPER);
        PokemonRarity.add("Riolu", Rarity.COPPER);
        PokemonRarity.add("Lucario", Rarity.SILVER);
        PokemonRarity.add("Hippopotas", Rarity.COPPER);
        PokemonRarity.add("Hippowdon", Rarity.SILVER);
        PokemonRarity.add("Skorupi", Rarity.COPPER);
        PokemonRarity.add("Drapion", Rarity.SILVER);
        PokemonRarity.add("Croagunk", Rarity.COPPER);
        PokemonRarity.add("Toxicroak", Rarity.SILVER);
        PokemonRarity.add("Carnivine", Rarity.COPPER);
        PokemonRarity.add("Finneon", Rarity.COPPER);
        PokemonRarity.add("Lumineon", Rarity.SILVER);
        PokemonRarity.add("Mantyke", Rarity.COPPER);
        PokemonRarity.add("Snover", Rarity.COPPER);
        PokemonRarity.add("Abomasnow", Rarity.SILVER);
        PokemonRarity.add("Weavile", Rarity.SILVER);
        PokemonRarity.add("Magnezone", Rarity.GOLD);
        PokemonRarity.add("Lickilicky", Rarity.SILVER);
        PokemonRarity.add("Rhyperior", Rarity.GOLD);
        PokemonRarity.add("Tangrowth", Rarity.SILVER);
        PokemonRarity.add("Electivire", Rarity.GOLD);
        PokemonRarity.add("Magmortar", Rarity.GOLD);
        PokemonRarity.add("Togekiss", Rarity.GOLD);
        PokemonRarity.add("Yanmega", Rarity.SILVER);
        PokemonRarity.add("Leafeon", Rarity.SILVER);
        PokemonRarity.add("Glaceon", Rarity.SILVER);
        PokemonRarity.add("Gliscor", Rarity.SILVER);
        PokemonRarity.add("Mamoswine", Rarity.GOLD);
        PokemonRarity.add("Porygonz", Rarity.GOLD);
        PokemonRarity.add("Gallade", Rarity.GOLD);
        PokemonRarity.add("Probopass", Rarity.SILVER);
        PokemonRarity.add("Dusknoir", Rarity.GOLD);
        PokemonRarity.add("Froslass", Rarity.SILVER);
        PokemonRarity.add("Rotom", Rarity.GOLD);
        PokemonRarity.add("Uxie", Rarity.MYTHICAL);
        PokemonRarity.add("Mesprit", Rarity.MYTHICAL);
        PokemonRarity.add("Azelf", Rarity.MYTHICAL);
        PokemonRarity.add("Dialga", Rarity.LEGENDARY);
        PokemonRarity.add("Palkia", Rarity.LEGENDARY);
        PokemonRarity.add("Heatran", Rarity.LEGENDARY);
        PokemonRarity.add("Regigigas", Rarity.LEGENDARY);
        PokemonRarity.add("Giratina", Rarity.LEGENDARY);
        PokemonRarity.add("Origin Giratina", Rarity.EXTREME);
        PokemonRarity.add("Cresselia", Rarity.LEGENDARY);
        PokemonRarity.add("Phione", Rarity.MYTHICAL);
        PokemonRarity.add("Manaphy", Rarity.MYTHICAL);
        PokemonRarity.add("Darkrai", Rarity.LEGENDARY);
        PokemonRarity.add("Shaymin", Rarity.MYTHICAL);
        PokemonRarity.add("Shaymin Sky", Rarity.EXTREME);
        PokemonRarity.add("Arceus", Rarity.LEGENDARY);

        //Gen 5

        PokemonRarity.add("Victini", Rarity.MYTHICAL);
        PokemonRarity.add("Snivy", Rarity.SILVER);
        PokemonRarity.add("Servine", Rarity.GOLD);
        PokemonRarity.add("Serperior", Rarity.DIAMOND);
        PokemonRarity.add("Tepig", Rarity.SILVER);
        PokemonRarity.add("Pignite", Rarity.GOLD);
        PokemonRarity.add("Emboar", Rarity.DIAMOND);
        PokemonRarity.add("Oshawott", Rarity.SILVER);
        PokemonRarity.add("Dewott", Rarity.GOLD);
        PokemonRarity.add("Samurott", Rarity.DIAMOND);
        PokemonRarity.add("Patrat", Rarity.COPPER);
        PokemonRarity.add("Watchog", Rarity.SILVER);
        PokemonRarity.add("Lillipup", Rarity.COPPER);
        PokemonRarity.add("Herdier", Rarity.SILVER);
        PokemonRarity.add("Stoutland", Rarity.GOLD);
        PokemonRarity.add("Purrloin", Rarity.COPPER);
        PokemonRarity.add("Liepard", Rarity.SILVER);
        PokemonRarity.add("Pansage", Rarity.COPPER);
        PokemonRarity.add("Simisage", Rarity.SILVER);
        PokemonRarity.add("Pansear", Rarity.COPPER);
        PokemonRarity.add("Simisear", Rarity.SILVER);
        PokemonRarity.add("Panpour", Rarity.COPPER);
        PokemonRarity.add("Simipour", Rarity.SILVER);
        PokemonRarity.add("Munna", Rarity.COPPER);
        PokemonRarity.add("Musharna", Rarity.SILVER);
        PokemonRarity.add("Pidove", Rarity.COPPER);
        PokemonRarity.add("Tranquill", Rarity.SILVER);
        PokemonRarity.add("Unfezant", Rarity.GOLD);
        PokemonRarity.add("Blitzle", Rarity.COPPER);
        PokemonRarity.add("Zebstrika", Rarity.SILVER);
        PokemonRarity.add("Roggenrola", Rarity.COPPER);
        PokemonRarity.add("Boldore", Rarity.SILVER);
        PokemonRarity.add("Gigalith", Rarity.GOLD);
        PokemonRarity.add("Woobat", Rarity.COPPER);
        PokemonRarity.add("Swoobat", Rarity.SILVER);
        PokemonRarity.add("Drilbur", Rarity.COPPER);
        PokemonRarity.add("Excadrill", Rarity.SILVER);
        PokemonRarity.add("Audino", Rarity.SILVER);
        PokemonRarity.add("Timburr", Rarity.COPPER);
        PokemonRarity.add("Gurdurr", Rarity.SILVER);
        PokemonRarity.add("Conkeldurr", Rarity.GOLD);
        PokemonRarity.add("Tympole", Rarity.COPPER);
        PokemonRarity.add("Palpitoad", Rarity.SILVER);
        PokemonRarity.add("Seismitoad", Rarity.GOLD);
        PokemonRarity.add("Throh", Rarity.SILVER);
        PokemonRarity.add("Sawk", Rarity.SILVER);
        PokemonRarity.add("Sewaddle", Rarity.COPPER);
        PokemonRarity.add("Swadloon", Rarity.SILVER);
        PokemonRarity.add("Leavanny", Rarity.GOLD);
        PokemonRarity.add("Venipede", Rarity.COPPER);
        PokemonRarity.add("Whirlipede", Rarity.SILVER);
        PokemonRarity.add("Scolipede", Rarity.GOLD);
        PokemonRarity.add("Cottonee", Rarity.COPPER);
        PokemonRarity.add("Whimsicott", Rarity.SILVER);
        PokemonRarity.add("Petilil", Rarity.COPPER);
        PokemonRarity.add("Lilligant", Rarity.SILVER);
        PokemonRarity.add("Basculin", Rarity.COPPER);
        PokemonRarity.add("Sandile", Rarity.COPPER);
        PokemonRarity.add("Krokorok", Rarity.SILVER);
        PokemonRarity.add("Krookodile", Rarity.GOLD);
        PokemonRarity.add("Darumaka", Rarity.COPPER);
        PokemonRarity.add("Galarian Darumaka", Rarity.SILVER);
        PokemonRarity.add("Darmanitan", Rarity.SILVER);
        PokemonRarity.add("Galarian Darmanitan", Rarity.GOLD);
        PokemonRarity.add("Maractus", Rarity.SILVER);
        PokemonRarity.add("Dwebble", Rarity.COPPER);
        PokemonRarity.add("Crustle", Rarity.SILVER);
        PokemonRarity.add("Scraggy", Rarity.COPPER);
        PokemonRarity.add("Scrafty", Rarity.SILVER);
        PokemonRarity.add("Sigilyph", Rarity.SILVER);
        PokemonRarity.add("Yamask", Rarity.COPPER);
        PokemonRarity.add("Galarian Yamask", Rarity.SILVER);
        PokemonRarity.add("Cofagrigus", Rarity.SILVER);
        PokemonRarity.add("Tirtouga", Rarity.COPPER);
        PokemonRarity.add("Carracosta", Rarity.SILVER);
        PokemonRarity.add("Archen", Rarity.COPPER);
        PokemonRarity.add("Archeops", Rarity.SILVER);
        PokemonRarity.add("Trubbish", Rarity.COPPER);
        PokemonRarity.add("Garbodor", Rarity.SILVER);
        PokemonRarity.add("Zorua", Rarity.COPPER);
        PokemonRarity.add("Zoroark", Rarity.SILVER);
        PokemonRarity.add("Minccino", Rarity.COPPER);
        PokemonRarity.add("Cinccino", Rarity.SILVER);
        PokemonRarity.add("Gothita", Rarity.COPPER);
        PokemonRarity.add("Gothorita", Rarity.SILVER);
        PokemonRarity.add("Gothitelle", Rarity.GOLD);
        PokemonRarity.add("Solosis", Rarity.COPPER);
        PokemonRarity.add("Duosion", Rarity.SILVER);
        PokemonRarity.add("Reuniclus", Rarity.GOLD);
        PokemonRarity.add("Ducklett", Rarity.COPPER);
        PokemonRarity.add("Swanna", Rarity.SILVER);
        PokemonRarity.add("Vanillite", Rarity.COPPER);
        PokemonRarity.add("Vanillish", Rarity.SILVER);
        PokemonRarity.add("Vanilluxe", Rarity.GOLD);
        PokemonRarity.add("Deerling", Rarity.COPPER);
        PokemonRarity.add("Sawsbuck", Rarity.SILVER);
        PokemonRarity.add("Emolga", Rarity.SILVER);
        PokemonRarity.add("Karrablast", Rarity.COPPER);
        PokemonRarity.add("Escavalier", Rarity.SILVER);
        PokemonRarity.add("Foongus", Rarity.COPPER);
        PokemonRarity.add("Amoonguss", Rarity.SILVER);
        PokemonRarity.add("Frillish", Rarity.COPPER);
        PokemonRarity.add("Jellicent", Rarity.SILVER);
        PokemonRarity.add("Alomomola", Rarity.COPPER);
        PokemonRarity.add("Joltik", Rarity.COPPER);
        PokemonRarity.add("Galvantula", Rarity.SILVER);
        PokemonRarity.add("Ferroseed", Rarity.COPPER);
        PokemonRarity.add("Ferrothorn", Rarity.SILVER);
        PokemonRarity.add("Klink", Rarity.COPPER);
        PokemonRarity.add("Klang", Rarity.SILVER);
        PokemonRarity.add("Klinklang", Rarity.GOLD);
        PokemonRarity.add("Tynamo", Rarity.COPPER);
        PokemonRarity.add("Eelektrik", Rarity.SILVER);
        PokemonRarity.add("Eelektross", Rarity.GOLD);
        PokemonRarity.add("Elgyem", Rarity.COPPER);
        PokemonRarity.add("Beheeyem", Rarity.SILVER);
        PokemonRarity.add("Litwick", Rarity.COPPER);
        PokemonRarity.add("Lampent", Rarity.SILVER);
        PokemonRarity.add("Chandelure", Rarity.GOLD);
        PokemonRarity.add("Axew", Rarity.COPPER);
        PokemonRarity.add("Fraxure", Rarity.SILVER);
        PokemonRarity.add("Haxorus", Rarity.GOLD);
        PokemonRarity.add("Cubchoo", Rarity.COPPER);
        PokemonRarity.add("Beartic", Rarity.SILVER);
        PokemonRarity.add("Cryogonal", Rarity.SILVER);
        PokemonRarity.add("Shelmet", Rarity.COPPER);
        PokemonRarity.add("Accelgor", Rarity.SILVER);
        PokemonRarity.add("Stunfisk", Rarity.COPPER);
        PokemonRarity.add("Galarian Stunfisk", Rarity.SILVER);
        PokemonRarity.add("Mienfoo", Rarity.COPPER);
        PokemonRarity.add("Mienshao", Rarity.SILVER);
        PokemonRarity.add("Druddigon", Rarity.GOLD);
        PokemonRarity.add("Golett", Rarity.COPPER);
        PokemonRarity.add("Golurk", Rarity.SILVER);
        PokemonRarity.add("Pawniard", Rarity.COPPER);
        PokemonRarity.add("Bisharp", Rarity.SILVER);
        PokemonRarity.add("Bouffalant", Rarity.SILVER);
        PokemonRarity.add("Rufflet", Rarity.COPPER);
        PokemonRarity.add("Braviary", Rarity.SILVER);
        PokemonRarity.add("Vullaby", Rarity.COPPER);
        PokemonRarity.add("Mandibuzz", Rarity.SILVER);
        PokemonRarity.add("Heatmor", Rarity.SILVER);
        PokemonRarity.add("Durant", Rarity.SILVER);
        PokemonRarity.add("Deino", Rarity.COPPER);
        PokemonRarity.add("Zweilous", Rarity.SILVER);
        PokemonRarity.add("Hydreigon", Rarity.GOLD);
        PokemonRarity.add("Larvesta", Rarity.COPPER);
        PokemonRarity.add("Volcarona", Rarity.SILVER);
        PokemonRarity.add("Cobalion", Rarity.LEGENDARY);
        PokemonRarity.add("Terrakion", Rarity.LEGENDARY);
        PokemonRarity.add("Virizion", Rarity.LEGENDARY);
        PokemonRarity.add("Tornadus", Rarity.LEGENDARY);
        PokemonRarity.add("Tornadus Therian", Rarity.EXTREME);
        PokemonRarity.add("Thundurus", Rarity.LEGENDARY);
        PokemonRarity.add("Thundurus Therian", Rarity.EXTREME);
        PokemonRarity.add("Reshiram", Rarity.LEGENDARY);
        PokemonRarity.add("Zekrom", Rarity.LEGENDARY);
        PokemonRarity.add("Landorus", Rarity.LEGENDARY);
        PokemonRarity.add("Landorus Therian", Rarity.EXTREME);
        PokemonRarity.add("Kyurem", Rarity.LEGENDARY);
        PokemonRarity.add("Black Kyurem", Rarity.EXTREME);
        PokemonRarity.add("White Kyurem", Rarity.EXTREME);
        PokemonRarity.add("Keldeo", Rarity.LEGENDARY);
        PokemonRarity.add("Meloetta", Rarity.MYTHICAL);
        PokemonRarity.add("Meloetta Pirouette", Rarity.EXTREME);
        PokemonRarity.add("Genesect", Rarity.MYTHICAL);

        //Gen 6

        PokemonRarity.add("Chespin", Rarity.SILVER);
        PokemonRarity.add("Quilladin", Rarity.GOLD);
        PokemonRarity.add("Chesnaught", Rarity.DIAMOND);
        PokemonRarity.add("Fennekin", Rarity.SILVER);
        PokemonRarity.add("Braixen", Rarity.GOLD);
        PokemonRarity.add("Delphox", Rarity.DIAMOND);
        PokemonRarity.add("Froakie", Rarity.SILVER);
        PokemonRarity.add("Frogadier", Rarity.GOLD);
        PokemonRarity.add("Greninja", Rarity.DIAMOND);
        PokemonRarity.add("Ash Greninja", Rarity.PLATINUM);
        PokemonRarity.add("Bunnelby", Rarity.COPPER);
        PokemonRarity.add("Diggersby", Rarity.SILVER);
        PokemonRarity.add("Fletchling", Rarity.COPPER);
        PokemonRarity.add("Fletchinder", Rarity.SILVER);
        PokemonRarity.add("Talonflame", Rarity.GOLD);
        PokemonRarity.add("Scatterbug", Rarity.COPPER);
        PokemonRarity.add("Spewpa", Rarity.SILVER);
        PokemonRarity.add("Vivillon", Rarity.GOLD);
        PokemonRarity.add("Litleo", Rarity.COPPER);
        PokemonRarity.add("Pyroar", Rarity.SILVER);
        PokemonRarity.add("Flabebe", Rarity.COPPER);
        PokemonRarity.add("Floette", Rarity.SILVER);
        PokemonRarity.add("Florges", Rarity.GOLD);
        PokemonRarity.add("Skiddo", Rarity.COPPER);
        PokemonRarity.add("Gogoat", Rarity.SILVER);
        PokemonRarity.add("Pancham", Rarity.COPPER);
        PokemonRarity.add("Pangoro", Rarity.SILVER);
        PokemonRarity.add("Furfrou", Rarity.SILVER);
        PokemonRarity.add("Espurr", Rarity.COPPER);
        PokemonRarity.add("Meowstic", Rarity.SILVER);
        PokemonRarity.add("Honedge", Rarity.COPPER);
        PokemonRarity.add("Doublade", Rarity.SILVER);
        PokemonRarity.add("Aegislash", Rarity.GOLD);
        PokemonRarity.add("Aegislash Blade", Rarity.GOLD);
        PokemonRarity.add("Spritzee", Rarity.COPPER);
        PokemonRarity.add("Aromatisse", Rarity.SILVER);
        PokemonRarity.add("Swirlix", Rarity.COPPER);
        PokemonRarity.add("Slurpuff", Rarity.SILVER);
        PokemonRarity.add("Inkay", Rarity.COPPER);
        PokemonRarity.add("Malamar", Rarity.SILVER);
        PokemonRarity.add("Binacle", Rarity.COPPER);
        PokemonRarity.add("Barbaracle", Rarity.SILVER);
        PokemonRarity.add("Skrelp", Rarity.COPPER);
        PokemonRarity.add("Dragalge", Rarity.SILVER);
        PokemonRarity.add("Clauncher", Rarity.COPPER);
        PokemonRarity.add("Clawitzer", Rarity.SILVER);
        PokemonRarity.add("Helioptile", Rarity.COPPER);
        PokemonRarity.add("Heliolisk", Rarity.SILVER);
        PokemonRarity.add("Tyrunt", Rarity.COPPER);
        PokemonRarity.add("Tyrantrum", Rarity.SILVER);
        PokemonRarity.add("Amaura", Rarity.COPPER);
        PokemonRarity.add("Aurorus", Rarity.SILVER);
        PokemonRarity.add("Sylveon", Rarity.SILVER);
        PokemonRarity.add("Hawlucha", Rarity.SILVER);
        PokemonRarity.add("Dedenne", Rarity.COPPER);
        PokemonRarity.add("Carbink", Rarity.SILVER);
        PokemonRarity.add("Goomy", Rarity.COPPER);
        PokemonRarity.add("Sliggoo", Rarity.SILVER);
        PokemonRarity.add("Goodra", Rarity.GOLD);
        PokemonRarity.add("Klefki", Rarity.COPPER);
        PokemonRarity.add("Phantump", Rarity.COPPER);
        PokemonRarity.add("Trevenant", Rarity.SILVER);
        PokemonRarity.add("Pumpkaboo", Rarity.COPPER);
        PokemonRarity.add("Gourgeist", Rarity.SILVER);
        PokemonRarity.add("Bergmite", Rarity.COPPER);
        PokemonRarity.add("Avalugg", Rarity.SILVER);
        PokemonRarity.add("Noibat", Rarity.COPPER);
        PokemonRarity.add("Noivern", Rarity.SILVER);
        PokemonRarity.add("Xerneas", Rarity.LEGENDARY);
        PokemonRarity.add("Yveltal", Rarity.LEGENDARY);
        PokemonRarity.add("Zygarde", Rarity.LEGENDARY);
        PokemonRarity.add("Zygarde 10", Rarity.EXTREME);
        PokemonRarity.add("Zygarde Complete", Rarity.EXTREME);
        PokemonRarity.add("Diancie", Rarity.MYTHICAL);
        PokemonRarity.add("Hoopa", Rarity.MYTHICAL);
        PokemonRarity.add("Hoopa Unbound", Rarity.EXTREME);
        PokemonRarity.add("Volcanion", Rarity.LEGENDARY);

        //Gen 7

        PokemonRarity.add("Rowlet", Rarity.SILVER);
        PokemonRarity.add("Dartrix", Rarity.GOLD);
        PokemonRarity.add("Decidueye", Rarity.DIAMOND);
        PokemonRarity.add("Litten", Rarity.SILVER);
        PokemonRarity.add("Torracat", Rarity.GOLD);
        PokemonRarity.add("Incineroar", Rarity.DIAMOND);
        PokemonRarity.add("Popplio", Rarity.SILVER);
        PokemonRarity.add("Brionne", Rarity.GOLD);
        PokemonRarity.add("Primarina", Rarity.DIAMOND);
        PokemonRarity.add("Pikipek", Rarity.COPPER);
        PokemonRarity.add("Trumbeak", Rarity.SILVER);
        PokemonRarity.add("Toucannon", Rarity.GOLD);
        PokemonRarity.add("Yungoos", Rarity.COPPER);
        PokemonRarity.add("Gumshoos", Rarity.SILVER);
        PokemonRarity.add("Grubbin", Rarity.COPPER);
        PokemonRarity.add("Charjabug", Rarity.SILVER);
        PokemonRarity.add("Vikavolt", Rarity.GOLD);
        PokemonRarity.add("Crabrawler", Rarity.COPPER);
        PokemonRarity.add("Crabominable", Rarity.SILVER);
        PokemonRarity.add("Oricorio", Rarity.COPPER);
        PokemonRarity.add("Cutiefly", Rarity.COPPER);
        PokemonRarity.add("Ribombee", Rarity.SILVER);
        PokemonRarity.add("Rockruff", Rarity.COPPER);
        PokemonRarity.add("Lycanroc", Rarity.SILVER);
        PokemonRarity.add("Lycanroc Midnight", Rarity.SILVER);
        PokemonRarity.add("Lycanroc Dusk", Rarity.SILVER);
        PokemonRarity.add("Wishiwashi", Rarity.COPPER);
        PokemonRarity.add("Wishiwashi School", Rarity.PLATINUM);
        PokemonRarity.add("Mareanie", Rarity.COPPER);
        PokemonRarity.add("Toxapex", Rarity.SILVER);
        PokemonRarity.add("Mudbray", Rarity.COPPER);
        PokemonRarity.add("Mudsdale", Rarity.SILVER);
        PokemonRarity.add("Dewpider", Rarity.COPPER);
        PokemonRarity.add("Araquanid", Rarity.SILVER);
        PokemonRarity.add("Fomantis", Rarity.COPPER);
        PokemonRarity.add("Lurantis", Rarity.SILVER);
        PokemonRarity.add("Morelull", Rarity.COPPER);
        PokemonRarity.add("Shiinotic", Rarity.SILVER);
        PokemonRarity.add("Salandit", Rarity.COPPER);
        PokemonRarity.add("Salazzle", Rarity.SILVER);
        PokemonRarity.add("Stufful", Rarity.COPPER);
        PokemonRarity.add("Bewear", Rarity.SILVER);
        PokemonRarity.add("Bounsweet", Rarity.COPPER);
        PokemonRarity.add("Steenee", Rarity.SILVER);
        PokemonRarity.add("Tsareena", Rarity.GOLD);
        PokemonRarity.add("Comfey", Rarity.COPPER);
        PokemonRarity.add("Oranguru", Rarity.SILVER);
        PokemonRarity.add("Passimian", Rarity.SILVER);
        PokemonRarity.add("Wimpod", Rarity.COPPER);
        PokemonRarity.add("Golisopod", Rarity.SILVER);
        PokemonRarity.add("Sandygast", Rarity.COPPER);
        PokemonRarity.add("Palossand", Rarity.SILVER);
        PokemonRarity.add("Pyukumuku", Rarity.SILVER);
        PokemonRarity.add("Type Null", Rarity.PLATINUM);
        PokemonRarity.add("Silvally", Rarity.PLATINUM);
        PokemonRarity.add("Minior", Rarity.COPPER);
        PokemonRarity.add("Minior Core", Rarity.SILVER);
        PokemonRarity.add("Komala", Rarity.SILVER);
        PokemonRarity.add("Turtonator", Rarity.SILVER);
        PokemonRarity.add("Togedemaru", Rarity.SILVER);
        PokemonRarity.add("Mimikyu", Rarity.PLATINUM);
        PokemonRarity.add("Bruxish", Rarity.SILVER);
        PokemonRarity.add("Drampa", Rarity.SILVER);
        PokemonRarity.add("Dhelmise", Rarity.SILVER);
        PokemonRarity.add("Jangmo O", Rarity.COPPER);
        PokemonRarity.add("Hakamo O", Rarity.SILVER);
        PokemonRarity.add("Kommo O", Rarity.GOLD);
        PokemonRarity.add("Tapu Koko", Rarity.PLATINUM);
        PokemonRarity.add("Tapu Lele", Rarity.PLATINUM);
        PokemonRarity.add("Tapu Bulu", Rarity.PLATINUM);
        PokemonRarity.add("Tapu Fini", Rarity.PLATINUM);
        PokemonRarity.add("Cosmog", Rarity.LEGENDARY);
        PokemonRarity.add("Cosmoem", Rarity.LEGENDARY);
        PokemonRarity.add("Solgaleo", Rarity.LEGENDARY);
        PokemonRarity.add("Lunala", Rarity.LEGENDARY);
        PokemonRarity.add("Nihilego", Rarity.LEGENDARY);
        PokemonRarity.add("Buzzwole", Rarity.LEGENDARY);
        PokemonRarity.add("Pheromosa", Rarity.LEGENDARY);
        PokemonRarity.add("Xurkitree", Rarity.LEGENDARY);
        PokemonRarity.add("Celesteela", Rarity.LEGENDARY);
        PokemonRarity.add("Kartana", Rarity.LEGENDARY);
        PokemonRarity.add("Guzzlord", Rarity.LEGENDARY);
        PokemonRarity.add("Necrozma", Rarity.LEGENDARY);
        PokemonRarity.add("Dusk Mane Necrozma", Rarity.EXTREME);
        PokemonRarity.add("Dawn Wings Necrozma", Rarity.EXTREME);
        PokemonRarity.add("Magearna", Rarity.MYTHICAL);
        PokemonRarity.add("Marshadow", Rarity.MYTHICAL);
        PokemonRarity.add("Poipole", Rarity.LEGENDARY);
        PokemonRarity.add("Naganadel", Rarity.LEGENDARY);
        PokemonRarity.add("Stakataka", Rarity.LEGENDARY);
        PokemonRarity.add("Blacephalon", Rarity.LEGENDARY);
        PokemonRarity.add("Zeraora", Rarity.MYTHICAL);
        PokemonRarity.add("Meltan", Rarity.PLATINUM);
        PokemonRarity.add("Melmetal", Rarity.MYTHICAL);

        //Gen 8

        PokemonRarity.add("Grookey", Rarity.SILVER);
        PokemonRarity.add("Thwacker", Rarity.GOLD);
        PokemonRarity.add("Rillaboom", Rarity.DIAMOND);
        PokemonRarity.add("Scorbunny", Rarity.SILVER);
        PokemonRarity.add("Raboot", Rarity.GOLD);
        PokemonRarity.add("Cinderace", Rarity.DIAMOND);
        PokemonRarity.add("Sobble", Rarity.SILVER);
        PokemonRarity.add("Drizzile", Rarity.GOLD);
        PokemonRarity.add("Inteleon", Rarity.DIAMOND);
        PokemonRarity.add("Skwovet", Rarity.COPPER);
        PokemonRarity.add("Greedent", Rarity.SILVER);
        PokemonRarity.add("Rookidee", Rarity.COPPER);
        PokemonRarity.add("Corvisquire", Rarity.SILVER);
        PokemonRarity.add("Corviknight", Rarity.GOLD);
        PokemonRarity.add("Blipbug", Rarity.COPPER);
        PokemonRarity.add("Dottler", Rarity.SILVER);
        PokemonRarity.add("Orbeetle", Rarity.GOLD);
        PokemonRarity.add("Nickit", Rarity.COPPER);
        PokemonRarity.add("Thievul", Rarity.SILVER);
        PokemonRarity.add("Gossifleur", Rarity.COPPER);
        PokemonRarity.add("Eldegoss", Rarity.SILVER);
        PokemonRarity.add("Wooloo", Rarity.COPPER);
        PokemonRarity.add("Dubwool", Rarity.SILVER);
        PokemonRarity.add("Chewtle", Rarity.COPPER);
        PokemonRarity.add("Drednaw", Rarity.SILVER);
        PokemonRarity.add("Yamper", Rarity.COPPER);
        PokemonRarity.add("Boltund", Rarity.SILVER);
        PokemonRarity.add("Rolycoly", Rarity.COPPER);
        PokemonRarity.add("Carkol", Rarity.SILVER);
        PokemonRarity.add("Coalossal", Rarity.GOLD);
        PokemonRarity.add("Applin", Rarity.COPPER);
        PokemonRarity.add("Flapple", Rarity.SILVER);
        PokemonRarity.add("Appletun", Rarity.SILVER);
        PokemonRarity.add("Silicobra", Rarity.COPPER);
        PokemonRarity.add("Sandaconda", Rarity.SILVER);
        PokemonRarity.add("Cramorant", Rarity.SILVER);
        PokemonRarity.add("Arrokuda", Rarity.COPPER);
        PokemonRarity.add("Barraskewda", Rarity.SILVER);
        PokemonRarity.add("Toxel", Rarity.COPPER);
        PokemonRarity.add("Toxtricity Low Key", Rarity.SILVER);
        PokemonRarity.add("Toxtricity Amped", Rarity.SILVER);
        PokemonRarity.add("Sizzlipede", Rarity.COPPER);
        PokemonRarity.add("Centiskorch", Rarity.SILVER);
        PokemonRarity.add("Clobbopus", Rarity.COPPER);
        PokemonRarity.add("Grapploct", Rarity.SILVER);
        PokemonRarity.add("Sinistea", Rarity.COPPER);
        PokemonRarity.add("Polteageist", Rarity.SILVER);
        PokemonRarity.add("Hatenna", Rarity.COPPER);
        PokemonRarity.add("Hattrem", Rarity.SILVER);
        PokemonRarity.add("Hatterene", Rarity.GOLD);
        PokemonRarity.add("Impidimp", Rarity.SILVER);
        PokemonRarity.add("Morgrem", Rarity.COPPER);
        PokemonRarity.add("Grimmsnarl", Rarity.GOLD);
        PokemonRarity.add("Obstagoon", Rarity.GOLD);
        PokemonRarity.add("Perrserker", Rarity.SILVER);
        PokemonRarity.add("Cursola", Rarity.SILVER);
        PokemonRarity.add("Sirfetchd", Rarity.SILVER);
        PokemonRarity.add("Mr Rime", Rarity.SILVER);
        PokemonRarity.add("Runerigus", Rarity.SILVER);
        PokemonRarity.add("Milcery", Rarity.COPPER);
        PokemonRarity.add("Alcremie", Rarity.SILVER);
        PokemonRarity.add("Falinks", Rarity.SILVER);
        PokemonRarity.add("Pincurchin", Rarity.SILVER);
        PokemonRarity.add("Snom", Rarity.COPPER);
        PokemonRarity.add("Frosmoth", Rarity.SILVER);
        PokemonRarity.add("Stonjourner", Rarity.SILVER);
        PokemonRarity.add("Eiscue", Rarity.SILVER);
        PokemonRarity.add("Indeedee", Rarity.SILVER);
        PokemonRarity.add("Morpeko", Rarity.SILVER);
        PokemonRarity.add("Cufant", Rarity.COPPER);
        PokemonRarity.add("Copperajah", Rarity.SILVER);
        PokemonRarity.add("Dracozolt", Rarity.SILVER);
        PokemonRarity.add("Arctozolt", Rarity.SILVER);
        PokemonRarity.add("Dracovish", Rarity.SILVER);
        PokemonRarity.add("Arctovish", Rarity.SILVER);
        PokemonRarity.add("Duraludon", Rarity.SILVER);
        PokemonRarity.add("Dreepy", Rarity.SILVER);
        PokemonRarity.add("Drakloak", Rarity.GOLD);
        PokemonRarity.add("Dragapult", Rarity.DIAMOND);
        PokemonRarity.add("Zacian", Rarity.LEGENDARY);
        PokemonRarity.add("Zamazenta", Rarity.LEGENDARY);
        PokemonRarity.add("Eternatus", Rarity.LEGENDARY);
        PokemonRarity.add("Kubfu", Rarity.LEGENDARY);
        PokemonRarity.add("Urshifu", Rarity.LEGENDARY);
        PokemonRarity.add("Urshifu Rapid Strike", Rarity.EXTREME);
        PokemonRarity.add("Zarude", Rarity.MYTHICAL);
        PokemonRarity.add("Regieleki", Rarity.LEGENDARY);
        PokemonRarity.add("Regidrago", Rarity.LEGENDARY);
        PokemonRarity.add("Glastrier", Rarity.LEGENDARY);
        PokemonRarity.add("Spectrier", Rarity.LEGENDARY);
        PokemonRarity.add("Calyrex", Rarity.LEGENDARY);
        PokemonRarity.add("Ice Rider Calyrex", Rarity.EXTREME);
        PokemonRarity.add("Shadow Rider Calyrex", Rarity.EXTREME);

        Collections.shuffle(SPAWNS);

        System.out.println("Spawn Master List Size: " + SPAWNS.size());
    }

    public static String getSpawn()
    {
        return SPAWNS.get(new Random().nextInt(SPAWNS.size()));
    }

    public static String getLegendarySpawn()
    {
        List<String> combined = new ArrayList<>();

        combined.addAll(LEGENDARY);
        combined.addAll(MYTHICAL);
        combined.addAll(ULTRA_BEAST);

        String spawn = combined.get(new Random().nextInt(combined.size()));

        return SPAWNS.contains(spawn) ? spawn : getLegendarySpawn();
    }

    public static void add(String name, Rarity r)
    {
        for(int i = 0; i < r.num; i++) SPAWNS.add(name);

        POKEMON_RARITIES.put(name, r);

        if(!Global.POKEMON.contains(name)) System.out.println("Typo in: " + name);
    }

    public enum Rarity
    {
        COPPER(100),
        SILVER(75),
        GOLD(50),
        DIAMOND(25),
        PLATINUM(15),
        MYTHICAL(10),
        LEGENDARY(5),
        EXTREME(1);

        public int num;
        Rarity(int num)
        {
            this.num = num;
        }
    }
}
